apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: {aws_access_key_id}
  AWS_SECRET_ACCESS_KEY: {aws_secret_access_key}
kind: Secret
metadata:
  name: {secret_name}
  namespace: {namespace}
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {service_account_name}
  namespace: {namespace}
secrets:
- name: {secret_name}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {authorization_policy_name}
  namespace: {namespace}
spec:
  rules:
  - {}
  selector:
    matchLabels:
      component: predictor # Inference Service Pod Label
